CREATE OR REPLACE PROCEDURE addBonusTime
  ( StartDate IN MEMBERCARD.VALIDATIONDATE%TYPE,
    EndDate IN MEMBERCARD.VALIDATIONDATE%TYPE,
    bonusTime IN NUMBER DEFAULT 90 ) AS
  CURSOR EligibleMember IS
    SELECT MEMBERCARD.CARDNO
    FROM MEMBERCARD
    WHERE VALIDATIONDATE >= StartDate
      AND VALIDATIONDATE <= EndDate
      AND EXPIRATIONDATE - VALIDATIONDATE > 180;
  thisMember EligibleMember%ROWTYPE;
BEGIN
  OPEN EligibleMember;
  LOOP
    FETCH EligibleMember INTO thisMember;
    EXIT WHEN EligibleMember%NOTFOUND;

    UPDATE MEMBERCARD
      SET EXPIRATIONDATE = EXPIRATIONDATE + bonusTime;
   END LOOP;
  CLOSE EligibleMember;
END;/
