CREATE OR REPLACE TRIGGER addNoOfClientTrigger
  AFTER INSERT ON CONTRACT
      FOR EACH ROW
DECLARE
  BONESEXPIRATIONDATE MEMBERCARD.EXPIRATIONDATE%TYPE;
BEGIN
  UPDATE FITNESSPROGRAM
    SET TOTALENROLLMENT = TOTALENROLLMENT + 1 WHERE PROGRAMID = :new.PROGRAMNO;
END;/
