CREATE OR REPLACE TRIGGER addTotalEnrollmentTrigger
  AFTER INSERT ON CONTRACT
      FOR EACH ROW
BEGIN
  UPDATE FITNESSPROGRAM
    SET TOTALENROLLMENT = TOTALENROLLMENT + 1
    WHERE PROGRAMID = :new.PROGRAMNO;
  UPDATE TRAINER
    SET NO_OF_CLIENTS = NO_OF_CLIENTS + 1
    WHERE TRAINERID = :new.TRAINERID;
END;/
